In [1]:
f

NameError: name 'f' is not defined

In [15]:
from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC, NuSVC
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neighbors import KNeighborsClassifier, RadiusNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from xgboost import XGBClassifier

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

import warnings
# Ignore all warnings
warnings.filterwarnings("ignore")

In [3]:
train = pd.read_csv('train.csv',index_col='id')
X_test = pd.read_csv('test.csv',index_col='id') 


In [4]:
y_train_all = train[ ['Pastry', 'Z_Scratch', 'K_Scatch', 'Stains', 'Dirtiness', 'Bumps', 'Other_Faults']]

In [5]:
y_train1 = y_train_all.Pastry
y_train2 = y_train_all.Z_Scratch
y_train3 = y_train_all.K_Scatch
y_train4 = y_train_all.Stains
y_train5 = y_train_all.Dirtiness
y_train6 = y_train_all.Bumps
y_train7 = y_train_all.Other_Faults

In [6]:
X_train_early = train.drop([ 'Pastry', 'Z_Scratch', 'K_Scatch', 'Stains','Dirtiness', 'Bumps', 'Other_Faults'], axis=1)

In [7]:
X_train1, X_cv1, y_train1, y_cv1 = train_test_split(X_train_early, y_train1, test_size=0.2, random_state=42,stratify=y_train1)
X_train2, X_cv2, y_train2, y_cv2 = train_test_split(X_train_early, y_train2, test_size=0.2, random_state=42,stratify=y_train2)
X_train3, X_cv3, y_train3, y_cv3 = train_test_split(X_train_early, y_train3, test_size=0.2, random_state=42,stratify=y_train3)
X_train4, X_cv4, y_train4, y_cv4 = train_test_split(X_train_early, y_train4, test_size=0.2, random_state=42,stratify=y_train4)
X_train5, X_cv5, y_train5, y_cv5 = train_test_split(X_train_early, y_train5, test_size=0.2, random_state=42,stratify=y_train5)
X_train6, X_cv6, y_train6, y_cv6 = train_test_split(X_train_early, y_train6, test_size=0.2, random_state=42,stratify=y_train6)
X_train7, X_cv7, y_train7, y_cv7 = train_test_split(X_train_early, y_train7, test_size=0.2, random_state=42,stratify=y_train7)


In [8]:
print(X_train1.shape, X_cv1.shape, y_train1.shape, y_cv1.shape)

(15375, 27) (3844, 27) (15375,) (3844,)


In [ ]:

# from scipy import stats

# # Calculate Z-scores for each column in X_train and X_cv
# z_scores_train = stats.zscore(X_train_early)
# z_scores_cv = stats.zscore(X_cv_early)

# # Define a threshold for outlier detection (e.g., 3 standard deviations)
# threshold = 3

# # Filter out rows with outliers in X_train
# X_train = X_train_early[(z_scores_train < threshold).all(axis=1)]

# # Filter out rows with outliers in X_cv
# X_cv= X_cv_early[(z_scores_cv < threshold).all(axis=1)]


# filtered_indices_train = X_train_early.index.difference(X_train.index)
# filtered_indices_cv = X_cv_early.index.difference(X_cv.index)

# # Remove the same rows from y_train_all and y_cv_all
# y_train_all = y_train_all.drop(filtered_indices_train)
# y_cv_all = y_cv_all.drop(filtered_indices_cv)

In [9]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
train_s1 = scaler.fit_transform(X_train1)
test_s1 = scaler.transform(X_test)
cv_s1 = scaler.transform(X_cv1)
# Convert the standardized array back to a DataFrame
X_train1 = pd.DataFrame(train_s1, columns=X_train1.columns)
X_test1 = pd.DataFrame(test_s1, columns=X_test.columns)
X_cv1 = pd.DataFrame(cv_s1, columns=X_cv1.columns)

In [10]:
# for column in train.columns:
#     plt.figure(figsize=(4, 2))
#     sns.kdeplot(train[{column}], color='skyblue')
#     plt.xlabel({column})
#     plt.ylabel('Density')
#     plt.title(f'Continuous Distribution of {column}')
#     plt.grid(axis='y', alpha=0.75)
#     plt.show()



In [11]:
# first we will go with outliers, later we remove them
# as the model performs very poor without removing outliers, so we are now removing outliers

first we will make a model to train first column then repeat the process from previous project

In [12]:
# y_train1 = y_train_all.Pastry
# y_train2 = y_train_all.Z_Scratch
# y_train3 = y_train_all.K_Scatch
# y_train4 = y_train_all.Stains
# y_train5 = y_train_all.Dirtiness
# y_train6 = y_train_all.Bumps
# y_train7 = y_train_all.Other_Faults

# y_cv1 = y_cv_all.Pastry 
# y_cv2 = y_cv_all.Z_Scratch 
# y_cv3 = y_cv_all.K_Scatch 
# y_cv4 = y_cv_all.Stains 
# y_cv5 = y_cv_all.Dirtiness 
# y_cv6 = y_cv_all.Bumps 
# y_cv7 = y_cv_all.Other_Faults

In [ ]:
#1

from sklearn.metrics import accuracy_score
# Balance the dataset
ros = RandomOverSampler(random_state=42)
X_train1, y_train1 = ros.fit_resample(X_train1, y_train1)

# List of classifiers
classifiers = [
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    GradientBoostingClassifier(),
    AdaBoostClassifier(),
    SVC(),
    NuSVC(),
    LogisticRegression(),
    SGDClassifier(),
    KNeighborsClassifier(),
#     RadiusNeighborsClassifier(),
    GaussianNB(),
    MultinomialNB(),
    LinearDiscriminantAnalysis(),
    QuadraticDiscriminantAnalysis(),
    XGBClassifier(),

    # Add more classifiers here
]

# Loop through each algorithm
for clf in classifiers:
    clf.fit(X_train1, y_train1)
    y_pred1 = clf.predict(X_cv1)
    accuracy1 = accuracy_score(y_cv1, y_pred1)
    cm1 = confusion_matrix(y_cv1, y_pred1)
    print(f"{clf.__class__.__name__}: Accuracy - {accuracy1}, Confusion Matrix -\n{cm1}")



In [ ]:
#2
from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC, NuSVC
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neighbors import KNeighborsClassifier, RadiusNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score
# Balance the dataset
ros = RandomOverSampler(random_state=42)
X_train2, y_train2 = ros.fit_resample(X_train2, y_train2)

# List of classifiers
classifiers = [
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    GradientBoostingClassifier(),
    AdaBoostClassifier(),
    SVC(),
    NuSVC(),
    LogisticRegression(),
    SGDClassifier(),
    KNeighborsClassifier(),
#     RadiusNeighborsClassifier(),
    GaussianNB(),
#     MultinomialNB(),
    LinearDiscriminantAnalysis(),
    QuadraticDiscriminantAnalysis(),
    XGBClassifier(),

    # Add more classifiers here
]

# Loop through each algorithm
for clf in classifiers:
    clf.fit(X_train2, y_train2)
    y_pred2 = clf.predict(X_cv2)
    accuracy2 = accuracy_score(y_cv2, y_pred2)
    cm2 = confusion_matrix(y_cv2, y_pred2)
    print(f"{clf.__class__.__name__}: Accuracy - {accuracy2}, Confusion Matrix -\n{cm2}")



In [20]:
#3. K_Scatch

from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC, NuSVC
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neighbors import KNeighborsClassifier, RadiusNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score
# Balance the dataset
ros = RandomOverSampler(random_state=42)
X_train3, y_train3 = ros.fit_resample(X_train3, y_train3)

# List of classifiers
classifiers = [
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    GradientBoostingClassifier(),
    AdaBoostClassifier(),
    SVC(),
    NuSVC(),
    LogisticRegression(),
    SGDClassifier(),
    KNeighborsClassifier(),
#     RadiusNeighborsClassifier(),
    GaussianNB(),
#     MultinomialNB(),
    LinearDiscriminantAnalysis(),
    QuadraticDiscriminantAnalysis(),
    XGBClassifier(),

    # Add more classifiers here
]

# Loop through each algorithm
for clf in classifiers:
    clf.fit(X_train3, y_train3)
    y_pred3 = clf.predict(X_cv3)
    accuracy3 = accuracy_score(y_cv3, y_pred3)
    cm3 = confusion_matrix(y_cv3, y_pred3)
    print(f"{clf.__class__.__name__}: Accuracy - {accuracy3}, Confusion Matrix -\n{cm3}")



DecisionTreeClassifier: Accuracy - 0.9347034339229969, Confusion Matrix -
[[3029  129]
 [ 122  564]]
RandomForestClassifier: Accuracy - 0.9609781477627471, Confusion Matrix -
[[3077   81]
 [  69  617]]
GradientBoostingClassifier: Accuracy - 0.9581165452653486, Confusion Matrix -
[[3039  119]
 [  42  644]]
AdaBoostClassifier: Accuracy - 0.9518730489073881, Confusion Matrix -
[[3018  140]
 [  45  641]]
SVC: Accuracy - 0.9386056191467221, Confusion Matrix -
[[3024  134]
 [ 102  584]]
NuSVC: Accuracy - 0.9380853277835588, Confusion Matrix -
[[3051  107]
 [ 131  555]]
LogisticRegression: Accuracy - 0.9456295525494277, Confusion Matrix -
[[3037  121]
 [  88  598]]
SGDClassifier: Accuracy - 0.9198751300728408, Confusion Matrix -
[[2955  203]
 [ 105  581]]
KNeighborsClassifier: Accuracy - 0.8943808532778356, Confusion Matrix -
[[2842  316]
 [  90  596]]
GaussianNB: Accuracy - 0.9484911550468262, Confusion Matrix -
[[3039  119]
 [  79  607]]
LinearDiscriminantAnalysis: Accuracy - 0.954474505723

In [23]:
#4. Stains

from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC, NuSVC
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neighbors import KNeighborsClassifier, RadiusNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score
# Balance the dataset
ros = RandomOverSampler(random_state=42)
X_train4, y_train4 = ros.fit_resample(X_train4, y_train4)

# List of classifiers
classifiers = [
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    GradientBoostingClassifier(),
    AdaBoostClassifier(),
    SVC(),
    NuSVC(),
    LogisticRegression(),
    SGDClassifier(),
    KNeighborsClassifier(),
#     RadiusNeighborsClassifier(),
    GaussianNB(),
#     MultinomialNB(),
    LinearDiscriminantAnalysis(),
    QuadraticDiscriminantAnalysis(),
    XGBClassifier(),

    # Add more classifiers here
]

# Loop through each algorithm
for clf in classifiers:
    clf.fit(X_train4, y_train4)
    y_pred4 = clf.predict(X_cv4)
    accuracy4 = accuracy_score(y_cv4, y_pred4)
    cm4 = confusion_matrix(y_cv4, y_pred4)
    print(f"{clf.__class__.__name__}: Accuracy - {accuracy4}, Confusion Matrix -\n{cm4}")



DecisionTreeClassifier: Accuracy - 0.977627471383975, Confusion Matrix -
[[3696   34]
 [  52   62]]
RandomForestClassifier: Accuracy - 0.9864724245577523, Confusion Matrix -
[[3707   23]
 [  29   85]]
GradientBoostingClassifier: Accuracy - 0.9823100936524454, Confusion Matrix -
[[3671   59]
 [   9  105]]
AdaBoostClassifier: Accuracy - 0.9797086368366286, Confusion Matrix -
[[3661   69]
 [   9  105]]
SVC: Accuracy - 0.5096253902185224, Confusion Matrix -
[[1855 1875]
 [  10  104]]
NuSVC: Accuracy - 0.7700312174817898, Confusion Matrix -
[[2859  871]
 [  13  101]]
LogisticRegression: Accuracy - 0.9310613943808532, Confusion Matrix -
[[3472  258]
 [   7  107]]
SGDClassifier: Accuracy - 0.9700832466181062, Confusion Matrix -
[[3722    8]
 [ 107    7]]
KNeighborsClassifier: Accuracy - 0.9497918834547346, Confusion Matrix -
[[3587  143]
 [  50   64]]
GaussianNB: Accuracy - 0.5809053069719042, Confusion Matrix -
[[2122 1608]
 [   3  111]]
LinearDiscriminantAnalysis: Accuracy - 0.9430280957336

In [24]:
#5 Dirtiness

from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC, NuSVC
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neighbors import KNeighborsClassifier, RadiusNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score
# Balance the dataset
ros = RandomOverSampler(random_state=42)
X_train5, y_train5 = ros.fit_resample(X_train5, y_train5)

# List of classifiers
classifiers = [
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    GradientBoostingClassifier(),
    AdaBoostClassifier(),
    SVC(),
    NuSVC(),
    LogisticRegression(),
    SGDClassifier(),
    KNeighborsClassifier(),
#     RadiusNeighborsClassifier(),
    GaussianNB(),
#     MultinomialNB(),
    LinearDiscriminantAnalysis(),
    QuadraticDiscriminantAnalysis(),
    XGBClassifier(),

    # Add more classifiers here
]

# Loop through each algorithm
for clf in classifiers:
    clf.fit(X_train5, y_train5)
    y_pred5 = clf.predict(X_cv5)
    accuracy5 = accuracy_score(y_cv5, y_pred5)
    cm5 = confusion_matrix(y_cv5, y_pred5)
    print(f"{clf.__class__.__name__}: Accuracy - {accuracy5}, Confusion Matrix -\n{cm5}")



DecisionTreeClassifier: Accuracy - 0.9638397502601457, Confusion Matrix -
[[3685   62]
 [  77   20]]
RandomForestClassifier: Accuracy - 0.9739854318418314, Confusion Matrix -
[[3728   19]
 [  81   16]]
GradientBoostingClassifier: Accuracy - 0.8597814776274714, Confusion Matrix -
[[3237  510]
 [  29   68]]
AdaBoostClassifier: Accuracy - 0.8218002081165453, Confusion Matrix -
[[3091  656]
 [  29   68]]
SVC: Accuracy - 0.4802289281997919, Confusion Matrix -
[[1781 1966]
 [  32   65]]
NuSVC: Accuracy - 0.5658168574401665, Confusion Matrix -
[[2126 1621]
 [  48   49]]
LogisticRegression: Accuracy - 0.6272112382934444, Confusion Matrix -
[[2350 1397]
 [  36   61]]
SGDClassifier: Accuracy - 0.9695629552549427, Confusion Matrix -
[[3727   20]
 [  97    0]]
KNeighborsClassifier: Accuracy - 0.9146722164412071, Confusion Matrix -
[[3496  251]
 [  77   20]]
GaussianNB: Accuracy - 0.22606659729448492, Confusion Matrix -
[[ 776 2971]
 [   4   93]]
LinearDiscriminantAnalysis: Accuracy - 0.74063475546

In [28]:
#6 Bumps

from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC, NuSVC
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neighbors import KNeighborsClassifier, RadiusNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score
# Balance the dataset
ros = RandomOverSampler(random_state=42)
X_train6, y_train6 = ros.fit_resample(X_train6, y_train6)

# List of classifiers
classifiers = [
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    GradientBoostingClassifier(),
    AdaBoostClassifier(),
    SVC(),
    NuSVC(),
    LogisticRegression(),
    SGDClassifier(),
    KNeighborsClassifier(),
#     RadiusNeighborsClassifier(),
    GaussianNB(),
#     MultinomialNB(),
    LinearDiscriminantAnalysis(),
    QuadraticDiscriminantAnalysis(),
    XGBClassifier(),

    # Add more classifiers here
]

# Loop through each algorithm
for clf in classifiers:
    clf.fit(X_train6, y_train6)
    y_pred6 = clf.predict(X_cv6)
    accuracy6 = accuracy_score(y_cv6, y_pred6)
    cm6 = confusion_matrix(y_cv6, y_pred6)
    print(f"{clf.__class__.__name__}: Accuracy - {accuracy6}, Confusion Matrix -\n{cm6}")



DecisionTreeClassifier: Accuracy - 0.7164412070759626, Confusion Matrix -
[[2356  535]
 [ 555  398]]
RandomForestClassifier: Accuracy - 0.77159209157128, Confusion Matrix -
[[2573  318]
 [ 560  393]]
GradientBoostingClassifier: Accuracy - 0.6925078043704475, Confusion Matrix -
[[1890 1001]
 [ 181  772]]
AdaBoostClassifier: Accuracy - 0.6698751300728408, Confusion Matrix -
[[1817 1074]
 [ 195  758]]
SVC: Accuracy - 0.4250780437044745, Confusion Matrix -
[[ 694 2197]
 [  13  940]]
NuSVC: Accuracy - 0.5946930280957337, Confusion Matrix -
[[1928  963]
 [ 595  358]]
LogisticRegression: Accuracy - 0.49921956295525494, Confusion Matrix -
[[1051 1840]
 [  85  868]]
SGDClassifier: Accuracy - 0.7484391259105099, Confusion Matrix -
[[2858   33]
 [ 934   19]]
KNeighborsClassifier: Accuracy - 0.5790842872008325, Confusion Matrix -
[[1701 1190]
 [ 428  525]]
GaussianNB: Accuracy - 0.44068678459937566, Confusion Matrix -
[[ 759 2132]
 [  18  935]]
LinearDiscriminantAnalysis: Accuracy - 0.657388137356

In [30]:
#7 Other_Faults

from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC, NuSVC
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neighbors import KNeighborsClassifier, RadiusNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score
# Balance the dataset
ros = RandomOverSampler(random_state=42)
X_train7, y_train7 = ros.fit_resample(X_train7, y_train7)

# List of classifiers
classifiers = [
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    GradientBoostingClassifier(),
    AdaBoostClassifier(),
    SVC(),
    NuSVC(),
    LogisticRegression(),
    SGDClassifier(),
    KNeighborsClassifier(),
#     RadiusNeighborsClassifier(),
    GaussianNB(),
#     MultinomialNB(),
    LinearDiscriminantAnalysis(),
    QuadraticDiscriminantAnalysis(),
    XGBClassifier(),

    # Add more classifiers here
]

# Loop through each algorithm
for clf in classifiers:
    clf.fit(X_train7, y_train7)
    y_pred7 = clf.predict(X_cv7)
    accuracy7 = accuracy_score(y_cv7, y_pred7)
    cm7 = confusion_matrix(y_cv7, y_pred7)
    print(f"{clf.__class__.__name__}: Accuracy - {accuracy7}, Confusion Matrix -\n{cm7}")



DecisionTreeClassifier: Accuracy - 0.5978147762747138, Confusion Matrix -
[[1760  772]
 [ 774  538]]
RandomForestClassifier: Accuracy - 0.6599895941727367, Confusion Matrix -
[[2050  482]
 [ 825  487]]
GradientBoostingClassifier: Accuracy - 0.6259105098855359, Confusion Matrix -
[[1466 1066]
 [ 372  940]]
AdaBoostClassifier: Accuracy - 0.6235691987513007, Confusion Matrix -
[[1472 1060]
 [ 387  925]]
SVC: Accuracy - 0.4966181061394381, Confusion Matrix -
[[ 689 1843]
 [  92 1220]]
NuSVC: Accuracy - 0.5694588969823101, Confusion Matrix -
[[1816  716]
 [ 939  373]]
LogisticRegression: Accuracy - 0.5127471383975026, Confusion Matrix -
[[ 808 1724]
 [ 149 1163]]
SGDClassifier: Accuracy - 0.6542663891779397, Confusion Matrix -
[[2452   80]
 [1249   63]]
KNeighborsClassifier: Accuracy - 0.5691987513007284, Confusion Matrix -
[[1509 1023]
 [ 633  679]]
GaussianNB: Accuracy - 0.49973985431841833, Confusion Matrix -
[[ 683 1849]
 [  74 1238]]
LinearDiscriminantAnalysis: Accuracy - 0.58662851196

In [ ]:
# DecisionTreeClassifier, RandomForestClassifier, XGBClassifier

In [13]:
# now i want to fit all data set.
scaler = StandardScaler()
train_s = scaler.fit_transform(X_train_early)
test_s = scaler.transform(X_test)

In [16]:
model1 = DecisionTreeClassifier(criterion='gini',max_depth= None, max_features='log2',min_samples_leaf= 1,
                                min_samples_split= 2)



model1.fit(train_s, y_train_all.Pastry)
y_pred1 = model1.predict(test_s)
submission = pd.DataFrame()
submission['id'] = X_test.index
submission['Pastry'] = y_pred1
submission
                                
                                
                                

id  Pastry
0      19219       1
1      19220       0
2      19221       0
3      19222       0
4      19223       0
...      ...     ...
12809  32028       0
12810  32029       0
12811  32030       0
12812  32031       1
12813  32032       0

[12814 rows x 2 columns]

In [17]:
model2 = RandomForestClassifier()


model2.fit(train_s, y_train_all.Z_Scratch)
y_pred2 = model2.predict(test_s)
# submission = pd.DataFrame()
# submission['id'] = X_test.index
submission['Z_Scratch'] = y_pred1
submission
            

id  Pastry  Z_Scratch
0      19219       1          1
1      19220       0          0
2      19221       0          0
3      19222       0          0
4      19223       0          0
...      ...     ...        ...
12809  32028       0          0
12810  32029       0          0
12811  32030       0          0
12812  32031       1          1
12813  32032       0          0

[12814 rows x 3 columns]

In [19]:
model3 = RandomForestClassifier()
model3.fit(train_s, y_train_all.K_Scatch)
y_pred3 = model3.predict(test_s)
# submission = pd.DataFrame()
# submission['id'] = X_test.index
submission['K_Scratch'] = y_pred3
submission
            

id  Pastry  Z_Scratch  K_Scratch
0      19219       1          1          0
1      19220       0          0          0
2      19221       0          0          0
3      19222       0          0          0
4      19223       0          0          0
...      ...     ...        ...        ...
12809  32028       0          0          0
12810  32029       0          0          0
12811  32030       0          0          1
12812  32031       1          1          0
12813  32032       0          0          1

[12814 rows x 4 columns]

In [26]:
model4 = RandomForestClassifier()
model4.fit(train_s, y_train_all.Stains)
y_pred4 = model4.predict(test_s)
# submission = pd.DataFrame()
# submission['id'] = X_test.index
submission['Stains'] = y_pred4
submission

id  Pastry  Z_Scratch  K_Scratch  Stains
0      19219       1          1          0       0
1      19220       0          0          0       0
2      19221       0          0          0       0
3      19222       0          0          0       0
4      19223       0          0          0       0
...      ...     ...        ...        ...     ...
12809  32028       0          0          0       0
12810  32029       0          0          0       0
12811  32030       0          0          1       0
12812  32031       1          1          0       0
12813  32032       0          0          1       0

[12814 rows x 5 columns]

In [27]:
model5 = RandomForestClassifier()
model5.fit(train_s, y_train_all.Dirtiness)
y_pred5 = model5.predict(test_s)
# submission = pd.DataFrame()
# submission['id'] = X_test.index
submission['Dirtiness'] = y_pred5
submission

id  Pastry  Z_Scratch  K_Scratch  Stains  Dirtiness
0      19219       1          1          0       0          0
1      19220       0          0          0       0          0
2      19221       0          0          0       0          0
3      19222       0          0          0       0          0
4      19223       0          0          0       0          0
...      ...     ...        ...        ...     ...        ...
12809  32028       0          0          0       0          0
12810  32029       0          0          0       0          0
12811  32030       0          0          1       0          0
12812  32031       1          1          0       0          0
12813  32032       0          0          1       0          0

[12814 rows x 6 columns]

In [29]:
model6 = RandomForestClassifier()
model6.fit(train_s, y_train_all.Dirtiness)
y_pred6 = model6.predict(test_s)
# submission = pd.DataFrame()
# submission['id'] = X_test.index
submission['Bumps'] = y_pred6
submission

id  Pastry  Z_Scratch  K_Scratch  Stains  Dirtiness  Bumps
0      19219       1          1          0       0          0      0
1      19220       0          0          0       0          0      0
2      19221       0          0          0       0          0      0
3      19222       0          0          0       0          0      0
4      19223       0          0          0       0          0      0
...      ...     ...        ...        ...     ...        ...    ...
12809  32028       0          0          0       0          0      0
12810  32029       0          0          0       0          0      0
12811  32030       0          0          1       0          0      0
12812  32031       1          1          0       0          0      0
12813  32032       0          0          1       0          0      0

[12814 rows x 7 columns]

In [31]:
model7 = RandomForestClassifier()
model7.fit(train_s, y_train_all.Other_Faults)
y_pred7 = model7.predict(test_s)
# submission = pd.DataFrame()
# submission['id'] = X_test.index
submission['Other_Faults'] = y_pred7
submission

id  Pastry  Z_Scratch  K_Scratch  Stains  Dirtiness  Bumps  \
0      19219       1          1          0       0          0      0   
1      19220       0          0          0       0          0      0   
2      19221       0          0          0       0          0      0   
3      19222       0          0          0       0          0      0   
4      19223       0          0          0       0          0      0   
...      ...     ...        ...        ...     ...        ...    ...   
12809  32028       0          0          0       0          0      0   
12810  32029       0          0          0       0          0      0   
12811  32030       0          0          1       0          0      0   
12812  32031       1          1          0       0          0      0   
12813  32032       0          0          1       0          0      0   

       Other_Faults  
0                 0  
1                 0  
2                 1  
3                 0  
4                 0  
...             ...  
12809             0  
12810             0  
12811             0  
12812             0  
12813             0  

[12814 rows x 8 columns]

In [34]:
submission.to_csv('submission.csv')