In [2]:
from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC, NuSVC
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neighbors import KNeighborsClassifier, RadiusNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from xgboost import XGBClassifier

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

import warnings
# Ignore all warnings
warnings.filterwarnings("ignore")

In [4]:
train = pd.read_csv('train.csv',index_col='id')
X_test = pd.read_csv('test.csv',index_col='id') 


In [5]:
y_train_all = train[ ['Pastry', 'Z_Scratch', 'K_Scatch', 'Stains', 'Dirtiness', 'Bumps', 'Other_Faults']]

In [6]:
y_train1 = y_train_all.Pastry
y_train2 = y_train_all.Z_Scratch
y_train3 = y_train_all.K_Scatch
y_train4 = y_train_all.Stains
y_train5 = y_train_all.Dirtiness
y_train6 = y_train_all.Bumps
y_train7 = y_train_all.Other_Faults

In [7]:
X_train_early = train.drop([ 'Pastry', 'Z_Scratch', 'K_Scatch', 'Stains','Dirtiness', 'Bumps', 'Other_Faults'], axis=1)

In [8]:
X_train1, X_cv1, y_train1, y_cv1 = train_test_split(X_train_early, y_train1, test_size=0.2, random_state=42,stratify=y_train1)
X_train2, X_cv2, y_train2, y_cv2 = train_test_split(X_train_early, y_train2, test_size=0.2, random_state=42,stratify=y_train2)
X_train3, X_cv3, y_train3, y_cv3 = train_test_split(X_train_early, y_train3, test_size=0.2, random_state=42,stratify=y_train3)
X_train4, X_cv4, y_train4, y_cv4 = train_test_split(X_train_early, y_train4, test_size=0.2, random_state=42,stratify=y_train4)
X_train5, X_cv5, y_train5, y_cv5 = train_test_split(X_train_early, y_train5, test_size=0.2, random_state=42,stratify=y_train5)
X_train6, X_cv6, y_train6, y_cv6 = train_test_split(X_train_early, y_train6, test_size=0.2, random_state=42,stratify=y_train6)
X_train7, X_cv7, y_train7, y_cv7 = train_test_split(X_train_early, y_train7, test_size=0.2, random_state=42,stratify=y_train7)


In [9]:
print(X_train1.shape, X_cv1.shape, y_train1.shape, y_cv1.shape)

(15375, 27) (3844, 27) (15375,) (3844,)


In [10]:
#1 
from scipy import stats

# Calculate Z-scores for each column in X_train and X_cv
z_scores_train = stats.zscore(X_train1)
z_scores_cv = stats.zscore(X_cv1)

# Define a threshold for outlier detection (e.g., 3 standard deviations)
threshold = 3

# Filter out rows with outliers in X_train
X_train0 = X_train1[(z_scores_train < threshold).all(axis=1)]

# Filter out rows with outliers in X_cv
X_cv0= X_cv1[(z_scores_cv < threshold).all(axis=1)]


filtered_indices_train = X_train1.index.difference(X_train0.index)
filtered_indices_cv = X_cv1.index.difference(X_cv0.index)

# Remove the same rows from y_train_all and y_cv_all
y_train1 = y_train1.drop(filtered_indices_train)
y_cv1 = y_cv1.drop(filtered_indices_cv)
X_train1,X_cv1=X_train0,X_cv0

In [11]:
print(X_train1.shape, X_cv1.shape, y_train1.shape, y_cv1.shape)

(13548, 27) (3384, 27) (13548,) (3384,)


In [12]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
train_s1 = scaler.fit_transform(X_train1)
test_s1 = scaler.transform(X_test)
cv_s1 = scaler.transform(X_cv1)
# Convert the standardized array back to a DataFrame
X_train1 = pd.DataFrame(train_s1, columns=X_train1.columns)
X_test1 = pd.DataFrame(test_s1, columns=X_test.columns)
X_cv1 = pd.DataFrame(cv_s1, columns=X_cv1.columns)

In [13]:
# for column in train.columns:
#     plt.figure(figsize=(4, 2))
#     sns.kdeplot(train[{column}], color='skyblue')
#     plt.xlabel({column})
#     plt.ylabel('Density')
#     plt.title(f'Continuous Distribution of {column}')
#     plt.grid(axis='y', alpha=0.75)
#     plt.show()



In [14]:
# first we will go with outliers, later we remove them
# as the model performs very poor without removing outliers, so we are now removing outliers

first we will make a model to train first column then repeat the process from previous project

In [15]:
# y_train1 = y_train_all.Pastry
# y_train2 = y_train_all.Z_Scratch
# y_train3 = y_train_all.K_Scatch
# y_train4 = y_train_all.Stains
# y_train5 = y_train_all.Dirtiness
# y_train6 = y_train_all.Bumps
# y_train7 = y_train_all.Other_Faults

# y_cv1 = y_cv_all.Pastry 
# y_cv2 = y_cv_all.Z_Scratch 
# y_cv3 = y_cv_all.K_Scatch 
# y_cv4 = y_cv_all.Stains 
# y_cv5 = y_cv_all.Dirtiness 
# y_cv6 = y_cv_all.Bumps 
# y_cv7 = y_cv_all.Other_Faults

In [16]:
X_train1.shape, y_train1.shape

((13548, 27), (13548,))

In [17]:
#1

from sklearn.metrics import accuracy_score
# Balance the dataset
ros = RandomOverSampler(random_state=42)
X_train1, y_train1 = ros.fit_resample(X_train1, y_train1)

# List of classifiers
classifiers = [
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    GradientBoostingClassifier(),
    AdaBoostClassifier(),
    SVC(),
    NuSVC(),
    LogisticRegression(),
    SGDClassifier(),
    KNeighborsClassifier(),
#     RadiusNeighborsClassifier(),
    GaussianNB(),
    MultinomialNB(),
    LinearDiscriminantAnalysis(),
    QuadraticDiscriminantAnalysis(),
    XGBClassifier(),

    # Add more classifiers here
]

# Loop through each algorithm
for clf in classifiers:
    clf.fit(X_train1, y_train1)
    y_pred1 = clf.predict(X_cv1)
    accuracy1 = accuracy_score(y_cv1, y_pred1)
    cm1 = confusion_matrix(y_cv1, y_pred1)
    print(f"{clf.__class__.__name__}: Accuracy - {accuracy1}, Confusion Matrix -\n{cm1}")



DecisionTreeClassifier: Accuracy - 0.8735224586288416, Confusion Matrix -
[[2897  214]
 [ 214   59]]
RandomForestClassifier: Accuracy - 0.9134160756501182, Confusion Matrix -
[[3072   39]
 [ 254   19]]
GradientBoostingClassifier: Accuracy - 0.7567966903073287, Confusion Matrix -
[[2342  769]
 [  54  219]]
AdaBoostClassifier: Accuracy - 0.7414302600472813, Confusion Matrix -
[[2293  818]
 [  57  216]]
SVC: Accuracy - 0.7130614657210402, Confusion Matrix -
[[2175  936]
 [  35  238]]
NuSVC: Accuracy - 0.6885342789598109, Confusion Matrix -
[[2087 1024]
 [  30  243]]
LogisticRegression: Accuracy - 0.7263593380614657, Confusion Matrix -
[[2226  885]
 [  41  232]]
SGDClassifier: Accuracy - 0.7907801418439716, Confusion Matrix -
[[2469  642]
 [  66  207]]
KNeighborsClassifier: Accuracy - 0.807919621749409, Confusion Matrix -
[[2589  522]
 [ 128  145]]
GaussianNB: Accuracy - 0.5460992907801419, Confusion Matrix -
[[1597 1514]
 [  22  251]]
MultinomialNB: Accuracy - 0.557033096926714, Confusion

In [18]:
#2
from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC, NuSVC
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neighbors import KNeighborsClassifier, RadiusNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score
# Balance the dataset
ros = RandomOverSampler(random_state=42)
X_train2, y_train2 = ros.fit_resample(X_train2, y_train2)

# List of classifiers
classifiers = [
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    GradientBoostingClassifier(),
    AdaBoostClassifier(),
    SVC(),
    NuSVC(),
    LogisticRegression(),
    SGDClassifier(),
    KNeighborsClassifier(),
#     RadiusNeighborsClassifier(),
    GaussianNB(),
#     MultinomialNB(),
    LinearDiscriminantAnalysis(),
    QuadraticDiscriminantAnalysis(),
    XGBClassifier(),

    # Add more classifiers here
]

# Loop through each algorithm
for clf in classifiers:
    clf.fit(X_train2, y_train2)
    y_pred2 = clf.predict(X_cv2)
    accuracy2 = accuracy_score(y_cv2, y_pred2)
    cm2 = confusion_matrix(y_cv2, y_pred2)
    print(f"{clf.__class__.__name__}: Accuracy - {accuracy2}, Confusion Matrix -\n{cm2}")



DecisionTreeClassifier: Accuracy - 0.9352237252861603, Confusion Matrix -
[[3481  133]
 [ 116  114]]
RandomForestClassifier: Accuracy - 0.9542143600416233, Confusion Matrix -
[[3545   69]
 [ 107  123]]
GradientBoostingClassifier: Accuracy - 0.9136316337148803, Confusion Matrix -
[[3312  302]
 [  30  200]]
AdaBoostClassifier: Accuracy - 0.9068678459937565, Confusion Matrix -
[[3283  331]
 [  27  203]]
SVC: Accuracy - 0.32466181061394384, Confusion Matrix -
[[1041 2573]
 [  23  207]]
NuSVC: Accuracy - 0.6220083246618107, Confusion Matrix -
[[2290 1324]
 [ 129  101]]
LogisticRegression: Accuracy - 0.6766389177939646, Confusion Matrix -
[[2441 1173]
 [  70  160]]
SGDClassifier: Accuracy - 0.3707075962539022, Confusion Matrix -
[[1220 2394]
 [  25  205]]
KNeighborsClassifier: Accuracy - 0.8090530697190427, Confusion Matrix -
[[3053  561]
 [ 173   57]]
GaussianNB: Accuracy - 0.5411030176899063, Confusion Matrix -
[[1856 1758]
 [   6  224]]
LinearDiscriminantAnalysis: Accuracy - 0.81191467221

In [19]:
#3. K_Scatch

from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC, NuSVC
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neighbors import KNeighborsClassifier, RadiusNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score
# Balance the dataset
ros = RandomOverSampler(random_state=42)
X_train3, y_train3 = ros.fit_resample(X_train3, y_train3)

# List of classifiers
classifiers = [
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    GradientBoostingClassifier(),
    AdaBoostClassifier(),
    SVC(),
    NuSVC(),
    LogisticRegression(),
    SGDClassifier(),
    KNeighborsClassifier(),
#     RadiusNeighborsClassifier(),
    GaussianNB(),
#     MultinomialNB(),
    LinearDiscriminantAnalysis(),
    QuadraticDiscriminantAnalysis(),
    XGBClassifier(),

    # Add more classifiers here
]

# Loop through each algorithm
for clf in classifiers:
    clf.fit(X_train3, y_train3)
    y_pred3 = clf.predict(X_cv3)
    accuracy3 = accuracy_score(y_cv3, y_pred3)
    cm3 = confusion_matrix(y_cv3, y_pred3)
    print(f"{clf.__class__.__name__}: Accuracy - {accuracy3}, Confusion Matrix -\n{cm3}")



DecisionTreeClassifier: Accuracy - 0.9409469302809573, Confusion Matrix -
[[3042  116]
 [ 111  575]]
RandomForestClassifier: Accuracy - 0.9604578563995838, Confusion Matrix -
[[3079   79]
 [  73  613]]
GradientBoostingClassifier: Accuracy - 0.9578563995837669, Confusion Matrix -
[[3039  119]
 [  43  643]]
AdaBoostClassifier: Accuracy - 0.9518730489073881, Confusion Matrix -
[[3018  140]
 [  45  641]]
SVC: Accuracy - 0.9386056191467221, Confusion Matrix -
[[3024  134]
 [ 102  584]]
NuSVC: Accuracy - 0.9380853277835588, Confusion Matrix -
[[3051  107]
 [ 131  555]]
LogisticRegression: Accuracy - 0.9456295525494277, Confusion Matrix -
[[3037  121]
 [  88  598]]
SGDClassifier: Accuracy - 0.9146722164412071, Confusion Matrix -
[[2919  239]
 [  89  597]]
KNeighborsClassifier: Accuracy - 0.8943808532778356, Confusion Matrix -
[[2842  316]
 [  90  596]]
GaussianNB: Accuracy - 0.9484911550468262, Confusion Matrix -
[[3039  119]
 [  79  607]]
LinearDiscriminantAnalysis: Accuracy - 0.954474505723

In [20]:
#4. Stains

from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC, NuSVC
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neighbors import KNeighborsClassifier, RadiusNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score
# Balance the dataset
ros = RandomOverSampler(random_state=42)
X_train4, y_train4 = ros.fit_resample(X_train4, y_train4)

# List of classifiers
classifiers = [
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    GradientBoostingClassifier(),
    AdaBoostClassifier(),
    SVC(),
    NuSVC(),
    LogisticRegression(),
    SGDClassifier(),
    KNeighborsClassifier(),
#     RadiusNeighborsClassifier(),
    GaussianNB(),
#     MultinomialNB(),
    LinearDiscriminantAnalysis(),
    QuadraticDiscriminantAnalysis(),
    XGBClassifier(),

    # Add more classifiers here
]

# Loop through each algorithm
for clf in classifiers:
    clf.fit(X_train4, y_train4)
    y_pred4 = clf.predict(X_cv4)
    accuracy4 = accuracy_score(y_cv4, y_pred4)
    cm4 = confusion_matrix(y_cv4, y_pred4)
    print(f"{clf.__class__.__name__}: Accuracy - {accuracy4}, Confusion Matrix -\n{cm4}")



DecisionTreeClassifier: Accuracy - 0.9797086368366286, Confusion Matrix -
[[3698   32]
 [  46   68]]
RandomForestClassifier: Accuracy - 0.9862122788761707, Confusion Matrix -
[[3708   22]
 [  31   83]]
GradientBoostingClassifier: Accuracy - 0.9823100936524454, Confusion Matrix -
[[3671   59]
 [   9  105]]
AdaBoostClassifier: Accuracy - 0.9797086368366286, Confusion Matrix -
[[3661   69]
 [   9  105]]
SVC: Accuracy - 0.5096253902185224, Confusion Matrix -
[[1855 1875]
 [  10  104]]
NuSVC: Accuracy - 0.7700312174817898, Confusion Matrix -
[[2859  871]
 [  13  101]]
LogisticRegression: Accuracy - 0.9310613943808532, Confusion Matrix -
[[3472  258]
 [   7  107]]
SGDClassifier: Accuracy - 0.9287200832466181, Confusion Matrix -
[[3480  250]
 [  24   90]]
KNeighborsClassifier: Accuracy - 0.9497918834547346, Confusion Matrix -
[[3587  143]
 [  50   64]]
GaussianNB: Accuracy - 0.5809053069719042, Confusion Matrix -
[[2122 1608]
 [   3  111]]
LinearDiscriminantAnalysis: Accuracy - 0.943028095733

In [21]:
#5 Dirtiness

from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC, NuSVC
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neighbors import KNeighborsClassifier, RadiusNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score
# Balance the dataset
ros = RandomOverSampler(random_state=42)
X_train5, y_train5 = ros.fit_resample(X_train5, y_train5)

# List of classifiers
classifiers = [
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    GradientBoostingClassifier(),
    AdaBoostClassifier(),
    SVC(),
    NuSVC(),
    LogisticRegression(),
    SGDClassifier(),
    KNeighborsClassifier(),
#     RadiusNeighborsClassifier(),
    GaussianNB(),
#     MultinomialNB(),
    LinearDiscriminantAnalysis(),
    QuadraticDiscriminantAnalysis(),
    XGBClassifier(),

    # Add more classifiers here
]

# Loop through each algorithm
for clf in classifiers:
    clf.fit(X_train5, y_train5)
    y_pred5 = clf.predict(X_cv5)
    accuracy5 = accuracy_score(y_cv5, y_pred5)
    cm5 = confusion_matrix(y_cv5, y_pred5)
    print(f"{clf.__class__.__name__}: Accuracy - {accuracy5}, Confusion Matrix -\n{cm5}")



DecisionTreeClassifier: Accuracy - 0.9609781477627471, Confusion Matrix -
[[3672   75]
 [  75   22]]
RandomForestClassifier: Accuracy - 0.9739854318418314, Confusion Matrix -
[[3731   16]
 [  84   13]]
GradientBoostingClassifier: Accuracy - 0.8597814776274714, Confusion Matrix -
[[3237  510]
 [  29   68]]
AdaBoostClassifier: Accuracy - 0.8218002081165453, Confusion Matrix -
[[3091  656]
 [  29   68]]
SVC: Accuracy - 0.4802289281997919, Confusion Matrix -
[[1781 1966]
 [  32   65]]
NuSVC: Accuracy - 0.5658168574401665, Confusion Matrix -
[[2126 1621]
 [  48   49]]
LogisticRegression: Accuracy - 0.6272112382934444, Confusion Matrix -
[[2350 1397]
 [  36   61]]
SGDClassifier: Accuracy - 0.9680020811654526, Confusion Matrix -
[[3721   26]
 [  97    0]]
KNeighborsClassifier: Accuracy - 0.9146722164412071, Confusion Matrix -
[[3496  251]
 [  77   20]]
GaussianNB: Accuracy - 0.22606659729448492, Confusion Matrix -
[[ 776 2971]
 [   4   93]]
LinearDiscriminantAnalysis: Accuracy - 0.74063475546

In [22]:
#6 Bumps

from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC, NuSVC
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neighbors import KNeighborsClassifier, RadiusNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score
# Balance the dataset
ros = RandomOverSampler(random_state=42)
X_train6, y_train6 = ros.fit_resample(X_train6, y_train6)

# List of classifiers
classifiers = [
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    GradientBoostingClassifier(),
    AdaBoostClassifier(),
    SVC(),
    NuSVC(),
    LogisticRegression(),
    SGDClassifier(),
    KNeighborsClassifier(),
#     RadiusNeighborsClassifier(),
    GaussianNB(),
#     MultinomialNB(),
    LinearDiscriminantAnalysis(),
    QuadraticDiscriminantAnalysis(),
    XGBClassifier(),

    # Add more classifiers here
]

# Loop through each algorithm
for clf in classifiers:
    clf.fit(X_train6, y_train6)
    y_pred6 = clf.predict(X_cv6)
    accuracy6 = accuracy_score(y_cv6, y_pred6)
    cm6 = confusion_matrix(y_cv6, y_pred6)
    print(f"{clf.__class__.__name__}: Accuracy - {accuracy6}, Confusion Matrix -\n{cm6}")



DecisionTreeClassifier: Accuracy - 0.7174817898022893, Confusion Matrix -
[[2367  524]
 [ 562  391]]
RandomForestClassifier: Accuracy - 0.7674297606659729, Confusion Matrix -
[[2563  328]
 [ 566  387]]
GradientBoostingClassifier: Accuracy - 0.6925078043704475, Confusion Matrix -
[[1890 1001]
 [ 181  772]]
AdaBoostClassifier: Accuracy - 0.6698751300728408, Confusion Matrix -
[[1817 1074]
 [ 195  758]]
SVC: Accuracy - 0.4250780437044745, Confusion Matrix -
[[ 694 2197]
 [  13  940]]
NuSVC: Accuracy - 0.5946930280957337, Confusion Matrix -
[[1928  963]
 [ 595  358]]
LogisticRegression: Accuracy - 0.49921956295525494, Confusion Matrix -
[[1051 1840]
 [  85  868]]
SGDClassifier: Accuracy - 0.43314255983350675, Confusion Matrix -
[[ 761 2130]
 [  49  904]]
KNeighborsClassifier: Accuracy - 0.5790842872008325, Confusion Matrix -
[[1701 1190]
 [ 428  525]]
GaussianNB: Accuracy - 0.44068678459937566, Confusion Matrix -
[[ 759 2132]
 [  18  935]]
LinearDiscriminantAnalysis: Accuracy - 0.657388137

In [23]:
#7 Other_Faults

from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC, NuSVC
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neighbors import KNeighborsClassifier, RadiusNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score
# Balance the dataset
ros = RandomOverSampler(random_state=42)
X_train7, y_train7 = ros.fit_resample(X_train7, y_train7)

# List of classifiers
classifiers = [
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    GradientBoostingClassifier(),
    AdaBoostClassifier(),
    SVC(),
    NuSVC(),
    LogisticRegression(),
    SGDClassifier(),
    KNeighborsClassifier(),
#     RadiusNeighborsClassifier(),
    GaussianNB(),
#     MultinomialNB(),
    LinearDiscriminantAnalysis(),
    QuadraticDiscriminantAnalysis(),
    XGBClassifier(),

    # Add more classifiers here
]

# Loop through each algorithm
for clf in classifiers:
    clf.fit(X_train7, y_train7)
    y_pred7 = clf.predict(X_cv7)
    accuracy7 = accuracy_score(y_cv7, y_pred7)
    cm7 = confusion_matrix(y_cv7, y_pred7)
    print(f"{clf.__class__.__name__}: Accuracy - {accuracy7}, Confusion Matrix -\n{cm7}")



DecisionTreeClassifier: Accuracy - 0.5996357960457857, Confusion Matrix -
[[1735  797]
 [ 742  570]]
RandomForestClassifier: Accuracy - 0.6670135275754423, Confusion Matrix -
[[2058  474]
 [ 806  506]]
GradientBoostingClassifier: Accuracy - 0.6256503642039543, Confusion Matrix -
[[1466 1066]
 [ 373  939]]
AdaBoostClassifier: Accuracy - 0.6235691987513007, Confusion Matrix -
[[1472 1060]
 [ 387  925]]
SVC: Accuracy - 0.4966181061394381, Confusion Matrix -
[[ 689 1843]
 [  92 1220]]
NuSVC: Accuracy - 0.5694588969823101, Confusion Matrix -
[[1816  716]
 [ 939  373]]
LogisticRegression: Accuracy - 0.5127471383975026, Confusion Matrix -
[[ 808 1724]
 [ 149 1163]]
SGDClassifier: Accuracy - 0.3868366285119667, Confusion Matrix -
[[ 208 2324]
 [  33 1279]]
KNeighborsClassifier: Accuracy - 0.5691987513007284, Confusion Matrix -
[[1509 1023]
 [ 633  679]]
GaussianNB: Accuracy - 0.49973985431841833, Confusion Matrix -
[[ 683 1849]
 [  74 1238]]
LinearDiscriminantAnalysis: Accuracy - 0.58662851196

In [24]:
# DecisionTreeClassifier, RandomForestClassifier, XGBClassifier

In [25]:
# now i want to fit all data set.
scaler = StandardScaler()
train_s = scaler.fit_transform(X_train_early)
test_s = scaler.transform(X_test)

In [26]:
model1 = DecisionTreeClassifier(criterion='gini',max_depth= None, max_features='log2',min_samples_leaf= 1,
                                min_samples_split= 2)



model1.fit(train_s, y_train_all.Pastry)
y_pred1 = model1.predict(test_s)
submission = pd.DataFrame()
submission['id'] = X_test.index
submission['Pastry'] = y_pred1
submission
                                
                                
                                

id  Pastry
0      19219       1
1      19220       0
2      19221       0
3      19222       0
4      19223       0
...      ...     ...
12809  32028       0
12810  32029       0
12811  32030       0
12812  32031       1
12813  32032       0

[12814 rows x 2 columns]

In [27]:
model2 = RandomForestClassifier()


model2.fit(train_s, y_train_all.Z_Scratch)
y_pred2 = model2.predict(test_s)
# submission = pd.DataFrame()
# submission['id'] = X_test.index
submission['Z_Scratch'] = y_pred1
submission
            

id  Pastry  Z_Scratch
0      19219       1          1
1      19220       0          0
2      19221       0          0
3      19222       0          0
4      19223       0          0
...      ...     ...        ...
12809  32028       0          0
12810  32029       0          0
12811  32030       0          0
12812  32031       1          1
12813  32032       0          0

[12814 rows x 3 columns]

In [28]:
model3 = RandomForestClassifier()
model3.fit(train_s, y_train_all.K_Scatch)
y_pred3 = model3.predict(test_s)
# submission = pd.DataFrame()
# submission['id'] = X_test.index
submission['K_Scratch'] = y_pred3
submission
            

id  Pastry  Z_Scratch  K_Scratch
0      19219       1          1          0
1      19220       0          0          0
2      19221       0          0          0
3      19222       0          0          0
4      19223       0          0          0
...      ...     ...        ...        ...
12809  32028       0          0          0
12810  32029       0          0          0
12811  32030       0          0          1
12812  32031       1          1          0
12813  32032       0          0          1

[12814 rows x 4 columns]

In [29]:
model4 = RandomForestClassifier()
model4.fit(train_s, y_train_all.Stains)
y_pred4 = model4.predict(test_s)
# submission = pd.DataFrame()
# submission['id'] = X_test.index
submission['Stains'] = y_pred4
submission

id  Pastry  Z_Scratch  K_Scratch  Stains
0      19219       1          1          0       0
1      19220       0          0          0       0
2      19221       0          0          0       0
3      19222       0          0          0       0
4      19223       0          0          0       0
...      ...     ...        ...        ...     ...
12809  32028       0          0          0       0
12810  32029       0          0          0       0
12811  32030       0          0          1       0
12812  32031       1          1          0       0
12813  32032       0          0          1       0

[12814 rows x 5 columns]

In [30]:
model5 = RandomForestClassifier()
model5.fit(train_s, y_train_all.Dirtiness)
y_pred5 = model5.predict(test_s)
# submission = pd.DataFrame()
# submission['id'] = X_test.index
submission['Dirtiness'] = y_pred5
submission

id  Pastry  Z_Scratch  K_Scratch  Stains  Dirtiness
0      19219       1          1          0       0          0
1      19220       0          0          0       0          0
2      19221       0          0          0       0          0
3      19222       0          0          0       0          0
4      19223       0          0          0       0          0
...      ...     ...        ...        ...     ...        ...
12809  32028       0          0          0       0          0
12810  32029       0          0          0       0          0
12811  32030       0          0          1       0          0
12812  32031       1          1          0       0          0
12813  32032       0          0          1       0          0

[12814 rows x 6 columns]

In [31]:
model6 = RandomForestClassifier()
model6.fit(train_s, y_train_all.Dirtiness)
y_pred6 = model6.predict(test_s)
# submission = pd.DataFrame()
# submission['id'] = X_test.index
submission['Bumps'] = y_pred6
submission

id  Pastry  Z_Scratch  K_Scratch  Stains  Dirtiness  Bumps
0      19219       1          1          0       0          0      0
1      19220       0          0          0       0          0      0
2      19221       0          0          0       0          0      0
3      19222       0          0          0       0          0      0
4      19223       0          0          0       0          0      0
...      ...     ...        ...        ...     ...        ...    ...
12809  32028       0          0          0       0          0      0
12810  32029       0          0          0       0          0      0
12811  32030       0          0          1       0          0      0
12812  32031       1          1          0       0          0      0
12813  32032       0          0          1       0          0      0

[12814 rows x 7 columns]

In [32]:
model7 = RandomForestClassifier()
model7.fit(train_s, y_train_all.Other_Faults)
y_pred7 = model7.predict(test_s)
# submission = pd.DataFrame()
# submission['id'] = X_test.index
submission['Other_Faults'] = y_pred7
submission

id  Pastry  Z_Scratch  K_Scratch  Stains  Dirtiness  Bumps  \
0      19219       1          1          0       0          0      0   
1      19220       0          0          0       0          0      0   
2      19221       0          0          0       0          0      0   
3      19222       0          0          0       0          0      0   
4      19223       0          0          0       0          0      0   
...      ...     ...        ...        ...     ...        ...    ...   
12809  32028       0          0          0       0          0      0   
12810  32029       0          0          0       0          0      0   
12811  32030       0          0          1       0          0      0   
12812  32031       1          1          0       0          0      0   
12813  32032       0          0          1       0          0      0   

       Other_Faults  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
...             ...  
12809             0  
12810             0  
12811             0  
12812             0  
12813             0  

[12814 rows x 8 columns]

In [33]:
submission.to_csv('submissionoutlie.csv')